sonar.projectKey=mernstack-auth-service
sonar.organization=RiyaTyagi

sonar.projectName=riya-mernstack-auth-service

sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.scm.exclusions.disabled=true
